### ISSUE TITLE
Potential improvements

### ISSUE THREAD

**Issue by willblev** [AtlasDev/AtlasDev#1]
Hi Dany,

This project is great! I've been tinkering with it to make my own personal site, so firstly I want to thank you for making the license open and for documenting your code!

Should you have any interest in returning to update this project, there are a few small things that I thought could make your terminal emulator interface even better.

1. Enable text copying: A visitor to your site can't copy text from the page (neither ctrl+c nor right click), so using your PGP key would be incredibly tedious ;-)
2. Use hyperlinks: In your projects section the URLs are not hyperlinks; since visitors can't simply copy the URL, viewing your projects is also somewhat tedious.
3. Fix src/registry/registry.ts line 46+: Currently, if an empty string (or all whitespace string) is entered by the visitor, the parser stalls & the visitor must reload the page. Instead, if a visitor enters an empty or all-whitespace string, the behavior should be to return the prompt on a new line.

Kind regards, 

Will

**Comment by dsluijk** [comment]
Hi,

Thank you for your interest in this project! I'm planning to make something different so this won't be updated, sorry. You are free to fork this and modify it as you like.

I am aware of these issues, and it probably has some more :). If you want to build something like this you might be better off building it from the ground up, using this as reference.

Thanks!
Dany
